name: create-cvs
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g resume-cli
      - run: npm install jsonresume-theme-actual
      - run: resume export geoff-clayton.pdf --theme actual
      - run: resume export geoff-clayton.html --theme actual
      - name: Archive artefacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf-cv
          path: geoff-clayton.pdf