name: create-cvs
on: [push]
jobs:
  create-cvs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g resume-cli
      - run: npm install jsonresume-theme-actual
      - run: resume export geoff-clayton.pdf --theme actual
      - run: resume export geoff-clayton.html --theme actual
      - name: Upload CV files
        uses: actions/upload-artifact@v3
        with:
          name: upload-cv-files
          path: geoff-clayton.*